- include: ../../common/tasks/setfacts.yml 

- name: install Java (RedHat)
  yum: name=java7 state=present
  when: ansible_os_family == "RedHat" 
  tags:
    - java

- include: oracle-java.yml
  when: ansible_os_family == "Debian"
