- include: ../../web2py/tasks/setfacts.yml

- name: checking if web2py downloaded
  stat: path="{{peyotlDir}}"
  register: downloaded

- name: delete phylesystem
  command: "rm -rf {{phylesystemDir}}"
  when: deletePhylesystem == True

- name: git clone/update phylesystem
  git: repo="{{phylesystemUrl0}}" dest="{{phylesystemDir}}" update=yes

- name: downloading studies
  command: "bash pull-studies.bash"
  args:
    chdir: "{{phylesystemDir}}"


#- name: downloading phylesystem1 dir
#  git: repo="{{phylesystemUrl1}}" dest="{{phylesystemDir1}}" update=yes

- name: download peyotl
  git: repo="{{peyotlUrl}}" dest="{{peyotlDir}}" version="{{peyotlVersion}}"
  when: downloaded.stat.exists == False

- name: peyotl install requirements
  command: "pip install -r requirements.txt"
  args:
    chdir: "{{peyotlDir}}"

- name: peyotl config file
  copy: src=.peyotl dest=~

- name: peyotl setup
  command: "python setup.py develop"
  args:
    chdir: "{{peyotlDir}}"

- name: checking if web2py downloaded
  stat: path="{{apiDir}}"
  register: downloaded

- name: download api
  git: repo="{{apiUrl}}" dest="{{apiDir}}" version="{{apiVersion}}"
  when: downloaded.stat.exists == False

- name: api - install requirements
  command: "pip install -r requirements.txt"
  args:
    chdir: "{{apiDir}}"

- name: copying api config
  action: copy src=config dest="{{configDest}}"

- name: download opentree git repo
  git: repo="{{opentreeUrl}}" dest="{{opentreeDir}}" version="{{opentreeVersion}}"

- name: opentree - install requirements
  command: "pip install -r requirements.txt"
  args:
    chdir: "{{opentreeDir}}"

- name: curator - install requirements
  command: "pip install -r requirements.txt"
  args:
    chdir: "{{curatorDir}}"

- name: create curator link to applications directory
  command: "ln -s {{curatorDir}} ."
  args:
    chdir: "{{web2pyAppDir}}"
    creates: "{{web2pyAppDir}}/{{curatorApp}}"

- name: create webapp link to applications directory
  command: "ln -s {{webappDir}} {{opentreeApp}}"
  args:
    chdir: "{{web2pyAppDir}}"
    creates: "{{web2pyAppDir}}/{{opentreeApp}}"

- name: copying curator config
  action: copy src=config.curator dest="{{curatorAppDir}}/private/config"

- name: copying curator db file
  action: copy src=db.py dest="{{curatorAppDir}}/models/"

- name: copying sqlite database
  command: "cp {{web2pyDir}}/storage.sqlite {{curatorAppDir}}/databases/"

- name: copying opentree config
  action: copy src=config.opentree dest="{{opentreeAppDir}}/private/config"

- name: change routing behaviour of web2py
  command: "cp {{opentreeDir}}/SITE.routes.py routes.py"
  args:
    chdir: "{{web2pyDir}}"

# install NCL
- name: git clone/update NCL
  git: repo="{{nclGit}}" dest="{{nclDir}}" update=yes
  tags: ncl

- name: NCL install
  command: "sh bootstrap.sh"
  args:
    chdir: "{{nclDir}}"
  tags:
    ncl

- name: NCL build directory
  command: "mkdir build"
  args:
    chdir: "{{nclDir}}"
  ignore_errors: yes
  tags:
    ncl

- name: NCL configure
  command: "./configure --prefix='{{opentreeToolsDir}}' --with-constfuncs=yes --disable-shared --with-reserveid"
  args:
    chdir: "{{nclDir}}"
  tags:
    ncl

- name: ncl make
  command: "make -j2"
  args:
    chdir: "{{nclDir}}"
  tags:
    ncl


- name: ncl check
  command: "make check"
  args:
    chdir: "{{nclDir}}"
  tags:
    ncl


- name: ncl install
  command: "make install"
  args:
    chdir: "{{nclDir}}"
  tags:
    ncl


- name: ncl installcheck
  command: "make installcheck"
  args:
    chdir: "{{nclDir}}"
  tags:
    ncl
# install 2nexml
- name: git clone/update 2nexml
  git: repo="{{toNexmlGit}}" dest="{{toNexmlDir}}" update=yes
  tags: tonexml

- name: 2nexml bootstrap
  command: "sh bootstrap.sh"
  args:
    chdir: "{{toNexmlDir}}"
  tags:
    tonexml

- name: 2nexml build directory
  command: "mkdir build"
  args:
    chdir: "{{toNexmlDir}}"
  ignore_errors: yes
  tags:
    tonexml

- name: 2nexml configure
  command: "./configure --prefix='{{opentreeToolsDir}}' --with-ncl='{{opentreeToolsDir}}'"
  args:
    chdir: "{{toNexmlDir}}"
  tags:
    tonexml

- name: 2nexml make
  command: "make -j2"
  args:
    chdir: "{{toNexmlDir}}"
  tags:
    tonexml

- name: 2nexml check
  command: "make check"
  args:
    chdir: "{{toNexmlDir}}"
  tags:
    tonexml


- name: 2nexml install
  command: "make install"
  args:
    chdir: "{{toNexmlDir}}"
  tags:
    tonexml


- name: 2nexml installcheck
  command: "make installcheck"
  args:
    chdir: "{{toNexmlDir}}"
  tags:
    tonexml

- name: restarting web2py
  shell: "/etc/init.d/web2py restart"
  when: ansible_os_family == "Debian"